### ISSUE TITLE
Crescendo needs more docs and examples

### ISSUE THREAD

**Issue by potatoqualitee** [MicrosoftDocs/PowerShell-Docs-Modules#101]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the module on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Module

Crescendo

### Links

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.crescendo/new-outputhandler?view=ps-modules

### Summary

There's no docs for the parameters and there's just one example. I had to use https://cs.github.com and search for other implementations.

### Suggested Fix

I'd like docs for all parameters. more examples including details on --- if I want to create a function to handle things, where does that go? how does script work? I figured out inline.

I'm also finding that the default behavior of Crescendo strips my output (`pastel color white` should be visually appealing) and I'm basically looking to bypass all processing. I don't know exactly what Streaming does other than to destroy my output.

**Comment by potatoqualitee** [comment]
Just found a bunch of docs in the schema! Perhaps that can be used as reference.

**Comment by sdwheeler** [comment]
Documenting the schema is on our TODO list.

**Comment by sdwheeler** [comment]
We have added new examples using the cmdlets to create definitions. Still working on a strategy for documenting the schema.
