### ISSUE TITLE
Typo in repo about url

### ISSUE THREAD

**Issue by floh96** [MicrosoftDocs/PowerShell-Docs-Modules#108]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the module on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Module

Crescendo

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs-Modules 

### Summary

https://github.com/MicrosoftDocs/PowerShell-Docs-Modules typo in about url of the repo see screenshot
![Screenshot 2022-09-25 144739](https://user-images.githubusercontent.com/49693964/192144280-dc699f89-dea5-4c8d-ab51-8aebe8d6113d.png)

**Comment by michaeltlombardi** [comment]
Thanks for filing this! I've updated the link.
