### ISSUE TITLE
Set-Secret clobber behavior needs further explanation

### ISSUE THREAD

**Issue by DonPwrShellHunt** [MicrosoftDocs/PowerShell-Docs-Modules#177]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the module on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Module

SecretManagement

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.secretmanagement/set-secret?view=ps-modules#description
- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.secretmanagement/set-secret?view=ps-modules#-noclobber

### Summary

The Microsoft.PowerShell.SecretManagement\Set-Secret documentation does not indicate if the secret name is compared with existing secrets in a case insensitive manner or not. This detail determines whether an Add or Replace is attempted to the vault and whether -NoClobber will generate an error if an existing secret is only different with respect to case sensitivity.

### Details

The behavior of SecretStore vault extension indicates that a case insensitive comparison is done on secret names. When an overwrite of a secret is performed, the secret name is changed to match the case submitted in the Set-Secret cmdlet. 

From the perspective of a vault extension author, I have not seen any parameters passed into the vault extension Set-Secret function that would inform clobber behavior of the extension logic. I am assuming that Microsoft.PowerShell.SecretManagement is in control of this behavior, which is why I elected to create this issue here.

Perhaps there is additional documentation that describes how this module implements clobber behavior and possibly what vaults extensions need to do for compatibility reasons.

**Comment by SydneyhSmith** [comment]
@andyleejordan also took a look at the code and is agreement with your analysis @sdwheeler of the behavior

**Comment by DonPwrShellHunt** [comment]
Further testing of case sensitive secret names has uncovered a [SecretManagement bug](https://github.com/PowerShell/SecretManagement/issues/95#issuecomment-1769292153) which make me wonder if any extension authors are using this configuration. This is not a recent issue (2021) and I'm hopeful we can at least resolve the failure mode of multiple secret names that differ only in case.

As for design docs for extension authors, I would like to see clobber and case sensitive (or not) secret names discussed. As Sean mentioned, when Get-Secret is called there are two scenarios to consider:

1. Case sensitive secret names are being used & the extension searches for an existing secret with the exact secret name requested. If found it returns the secret. If not, no secrets are returned.
2. Case insensitive secret name are being used. Existing secrets are scanned and compared (in a case insensitive way) to the secret name requested. Once a comparison is successful, that existing secret is returned. Again, if no secrets satisfy the comparison, no secret is returned.

Case 2 requires more overhead and depending on vault size could raise the possibility of using a SecretNamesCache for performance considerations. Perhaps having SecretManagement perform this caching rather than the extensions would be worth considering. 

Currently, SecretNameCompleter can find all secret names, even though I don't believe it is aware of the vault where a secret was found.

Just some ideas to consider.

**Comment by sdwheeler** [comment]
@DonPwrShellHunt This is good feedback, but you should open an issue in the source code repository.

- https://github.com/PowerShell/SecretManagement/issues/new/choose
- https://github.com/PowerShell/SecretStore/issues/new/choose
