### ISSUE TITLE
PSUseConsistentdentation should be PSUseConsistentIndentation

### ISSUE THREAD

**Issue by threatcat-ch** [MicrosoftDocs/PowerShell-Docs-Modules#181]
### Type of issue

Typo

### Feedback

The example in section [EXAMPLE 2 - Format the input script using the settings defined in a hashtable](https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-formatter#example-2-format-the-input-script-using-the-settings-defined-in-a-hashtable) uses the wrong rule name in `$settings`: `PSUseConsistentdentation` instead of `PSUseConsistentIndentation`.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-formatter?view=ps-modules

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-Modules/blob/main/reference/ps-modules/PSScriptAnalyzer/Invoke-Formatter.md

### Author

sdwheeler

### Document Id

be9c18ad-3d51-562f-4ea5-957a6e7a32f0

**Comment by sdwheeler** [comment]
@threatcat-ch I don't see the error you describe.

![image](https://github.com/MicrosoftDocs/PowerShell-Docs-Modules/assets/19415881/f618d1d0-18fd-447e-bc83-d52938ccf50d)
