### ISSUE TITLE
Command parameters are mentioned but not provided

### ISSUE THREAD

**Issue by randykroeger** [MicrosoftDocs/PowerShell-Docs-Modules#194]
### Type of issue

Missing information

### Feedback

I realize the command parameters are in another part of the documentation, but you're forcing the reader to hunt for them.  Redundancy is ok within documentation. At least provide a link where the command parameters you're referring, can be found.  

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.secretmanagement/test-secretvault?view=ps-modules

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-Modules/blob/main/reference/ps-modules/Microsoft.PowerShell.SecretManagement/Test-SecretVault.md

### Author

@sdwheeler

### Document Id

93fb10dd-4ecc-5743-8a76-968300a910e0

**Comment by sdwheeler** [comment]
I am assuming you meant "CommonParameter" instead of "Command parameters". The common parameters are listed in the markdown source files. The publishing system that builds the webpage is not rendering this information. We are working on a fix to the publishing system.
