### ISSUE TITLE
Microsoft.PowerShell.TextUtility should have help

### ISSUE THREAD

**Issue by ThomasNieto** [MicrosoftDocs/PowerShell-Docs-Modules#238]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Module

Crescendo

### Summary

`TextUtility` module should have help on the MS reference pages and be updatable.

### Content Type

Cmdlet Reference

**Comment by sdwheeler** [comment]
I don't disagree, but the PowerShell team is not prepared to support this module at this time. I will bring it up with the team again.

**Comment by sdwheeler** [comment]
I submitted a PR to the source code repo to add documentation.

https://github.com/PowerShell/TextUtility/pull/48

**Comment by SteveL-MSFT** [comment]
For now, we'll have docs in this repo and I'd like to eventually have a plan to get to a 1.0 release, but current resource constraints make that not feasible.

**Comment by sdwheeler** [comment]
We can publish docs to learn.microsoft.com one we get to a 1.0 release.
