### ISSUE TITLE
When Case Sensitivity is Needed in a HashTable

### ISSUE THREAD

**Issue by B-Art** [MicrosoftDocs/PowerShell-Docs-Modules#96]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Module

PSScriptAnalyzer

### Summary

As a User I need a HashTable to be Case Sensitive where the Data read is Case Sensitive.

A HashTable gives a very powerfull and fast acces to the Data wich is read, already is Case Sensitive.

So I disagree to the approach that a HashTable in powershell should always be Case Insenitive.

### Details

I use Pwsh to read Data from a serial input which uses coding that is Case Sensitive.

Transforming it into a Case Sensitive HasTable is the way easier than doing somekind of search and replace.

My approach is to keep read Data in the format it was when read.

I use a translation table to transform this Data into different Languages.

```
Set-Variable -Name TanitaTranslate -Value (
        (   '{0', 'Control Data 0'                                                      , 'Control Data 0'
        ), ('~0', 'Control Data 1'                                                      , 'Control Data 1'
        ), ('~1', 'Control Data 2'                                                      , 'Control Data 2'
        ), ('~2', 'Control Data 3'                                                      , 'Control Data 3'
        ), ('ZF', 'Impedance (50 kHz)'                                                  , 'Impedantie (50 Hz)'
        ), ('CS', 'Checksum'                                                            , 'Controlegetal'
        ), ('SN', 'Serial number'                                                       , 'Serieel nummer'
        ), ('MO', 'Model number'                                                        , 'Weegschaal Model'
...
        ), ('FW', 'Fat %'                                                               , 'Vet %'
        ), ('fW', 'Fat mass'                                                            , 'Vet massa'
        ), ('MW', 'Fat free mass'                                                       , 'Vetvrije massa'
        ), ('mW', 'Muscle mass'                                                         , 'Spier massa'
...
        ), ('wW', 'Body water mass'                                                     , 'Water massa'
        ), ('ww', 'Body water %'                                                        , 'Water %'
...
        )
    ) -Option Constant, AllScope -Force
```

### Content Type

Cmdlet Reference, Concept

### Proposed Title

When to use Case Sensitive HashTable

**Comment by sdwheeler** [comment]
@B-Art Does this have to do with a specific rule in PSScriptAnalyzer? It sounds like you are requesting a feature for PowerShell? If so, please file a feature request at https://aka.ms/psfeedback.
